### ISSUE TITLE
File reading with memory mapping

### ISSUE THREAD

**Issue by Strizzi12** [Strizzi12/PCCP1#1]

**Comment by Strizzi12** [comment]
This can be done with Boost library. This link may help
- https://www.eriksmistad.no/memory-mapped-files-using-the-boost-library/

**Comment by Strizzi12** [comment]
This can be done with Boost library. This link may help

    https://www.eriksmistad.no/memory-mapped-files-using-the-boost-library/

**Comment by Strizzi12** [comment]
This can be done with Boost library. This link may help
- https://www.eriksmistad.no/memory-mapped-files-using-the-boost-library/

**Comment by OkarinRintaro** [comment]
You can see more complex example in my repository: Signature. I use alignment to work with huge files.     
If you need anything, get back to me.

**Comment by Strizzi12** [comment]
Awesome, you made my day 👍 
This is actually an exercise from my university. :)

**Comment by OkarinRintaro** [comment]
Which university?
This test at the interview for me. :)
