### ISSUE TITLE
Access restriction and file is used by other process

### ISSUE THREAD

**Issue by Strizzi12** [Strizzi12/PCCP1#8]
![grafik](https://user-images.githubusercontent.com/15054772/33487934-46516cf0-d6af-11e7-862c-f99fc868e695.png)

**Comment by schoerg** [comment]
lel

**Comment by Strizzi12** [comment]
Solved with help from: **https://github.com/carlomilanesi/cpp-mmf/**
Included in commit: b18c10d851503374ff60f1d409ef700dea1d10d0
